# Generated by Django 4.0.6 on 2023-01-22 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
